function ETC_DisplayHelp(hObject,eventdata)
	
	strMsg = {'You can edit the pupil size and location using linear interpolation or',...
		'by using the pupil detection algorithm by selecting the radio buttons.',...
		'The detection is shown in red, while changes using the Epoch Annotation',...
		'are shown in blue overlaying the video frame. You can change the current',...
		'time point using the scroll wheel or by left-clicking on any trace plot.',...
		'Right-clicking in the zoomed-in traces will set a begin/end point, and',...
		'right-clicking a second time will interpolate/detect the pupil between',...
		'the two selected time points. Middle-mouse buttons set begin/end points',...
		'for a blinking/eyes-closed epoch. If you close the window, you can choose',...
		'to discard or save the data.',...
		'',...
		'Left mouse click: move to time-point',...
		'Middle mouse click in zoomed-in plot: set begin/end points for blinking',...
		'Right mouse click: set begin/end points for interpolate/detect epoch',...
		'Scroll wheel: move forward/backward through the video',...
		'',...
		'You can also use the following modifiers:',...
		'Middle+CTRL: remove blinking',...
		'Right+CTRL: force interpolate',...
		'Right+ALT: force detect',...
		'Scroll+CTRL: single-frame scroll',...
		'Scroll+ALT: 10x scroll',...
		'',...
		'For more information, see the manual.'};
	
	h=msgbox(strMsg,'TrackerChecker instructions');
	h.Children(end).Children.FontSize=10;
	h.Position=[300 300 350 260];
	movegui(h,'center');
end