function ETC_DisplayHelp(hObject,eventdata)
	%%
	strMsg = ['You can edit the pupil size and location using linear interpolation or ',...
		'by using the pupil detection algorithm by selecting the radio buttons. ',...
		'The detection is shown in red, while changes using the Epoch Annotation ',...
		'are shown in blue overlaying the video frame.',newline,...
		'You can change the current ',...
		'time point using the scroll wheel or by left-clicking on any trace plot. ',...
		'Right-clicking in the zoomed-in traces will set a begin/end point, and ' ,...
		'right-clicking a second time will interpolate/detect the pupil between ',...
		'the two selected time points. Middle-mouse buttons set begin/end points ',...
		'for a blinking/eyes-closed epoch. If you close the window, you can choose ',...
		'to discard or save the data.',newline,...
		newline,...
		'\bfLeft mouse click: \rmmove to time-point',newline,...
		'\bfMiddle click in zoomed-in plot: \rmset begin/end points for blinking',newline,...
		'\bfRight click: \rmset begin/end points for interpolate/detect epoch',newline,...
		'\bfScroll wheel: \rmmove forward/backward through the video',newline,...
		newline,...
		'You can also use the following modifiers when using the mouse:',newline,...
		'\bfMiddle+CTRL: \rmremove blinking',newline,...
		'\bfRight+CTRL: \rmforce interpolate',newline,...
		'\bfRight+ALT: \rmforce detect',newline,...
		'\bfScroll+CTRL: \rmsingle-frame scroll',newline,...
		'\bfScroll+ALT: \rm10x scroll',newline,...
		newline,...
		'Keyboard shortcuts:',newline,...
		'\bfLeft arrow: \rmSelect prior epoch',newline,...
		'\bfRight arrow: \rmSelect later epoch',newline,...
		'\bfb: \rmmark selected epoch as blink',newline,...
		'\bfn/k: \rmkeep selected epoch as non-blink',newline,...
		'\bfa: \rmapply selected epoch',newline,...
		'\bfi: \rminterpolate selected epoch',newline,...
		'\bfr: \rmrecalculate selected epoch',newline,...
		'\bfd: \rmdelete selected epoch',newline,...
		newline,...
		'For more information, see the manual.'];

	CreateStruct = struct;
	CreateStruct.Interpreter = 'tex';
	CreateStruct.WindowStyle = 'modal';
	h=msgbox(strMsg,'TrackerChecker instructions',CreateStruct);
	h.Children(end).Children.FontSize=10;
	h.Position=[300 300 350 480];
	movegui(h,'center');
end