function hPanelDatimex = ETP_genDataPanel(ptrMainGUI,vecLocation)
	
	%get globals
	global sETP;
	global sFigETP;
	
	%% set constants
	%nr of frames to import
	sETP.intImportPoints = 25;
	sETP.intImportStretch = 100;
	
	%unpack location vector
	vecX = [0.01 0.3 0.55 0.8];
	dblButtonWidth = 0.2;
	dblTextW = 0.13;
	dblEditW = 0.08;
	dblHeight = 0.8;
	%accept params / / # of frames / max avg / import
	
	%% make panel
	hPanelDatimex = uipanel('Parent',ptrMainGUI);
	vecColor = get(ptrMainGUI,'Color');
	set(hPanelDatimex,'Visible','off','Position',vecLocation,'BackgroundColor',vecColor,'Title','Data import/export','FontSize',10);
	
	%% accept params
	%button
	sFigETP.ptrButtonAcceptParams = uicontrol('Parent',hPanelDatimex,...
		'Units','normalized',...
		'Style','pushbutton',...
		'Position',[vecX(1) 0.1 dblButtonWidth dblHeight],...
		'FontSize',10,...
		'String',sprintf('Save & Exit'),...
		'Callback',{@ETP_AcceptParameters},...;
		'Tooltip','Accept current parameters for this video, save & exit');
	
	%%  / / # of frames
	%static text
	vecLocText = [vecX(2) 0.1 dblTextW dblHeight];
	ptrText=uitext('Parent',hPanelDatimex,...
		'Units','normalized',...
		'HorizontalAlignment','right',...
		'VerticalAlignment','middle',...
		'Position',vecLocText,...
		'FontSize',10,...
		'String','# of frames:');
	
	%edit text
	sFigETP.ptrEditImportPoints = uicontrol('Parent',hPanelDatimex,...
		'Units','normalized',...
		'Style','edit',...
		'Position',[vecLocText(1)+vecLocText(3)+0.01 0.1 dblEditW dblHeight],...
		'FontSize',10,...
		'String',sprintf('%.0f',sETP.intImportPoints),...
		'Tooltip','# of sample time points to import from video');
	
	%% / max avg /
	%static text
	vecLocText = [vecX(3) 0.1 dblTextW dblHeight];
	ptrText=uitext('Parent',hPanelDatimex,...
		'Units','normalized',...
		'HorizontalAlignment','right',...
		'VerticalAlignment','middle',...
		'Position',vecLocText,...
		'FontSize',10,...
		'String','Max. avg.:');
	
	%edit text
	sFigETP.ptrEditImportStretch = uicontrol('Parent',hPanelDatimex,...
		'Units','normalized',...
		'Style','edit',...
		'Position',[vecLocText(1)+vecLocText(3)+0.01 0.1 dblEditW dblHeight],...
		'FontSize',10,...
		'String',sprintf('%.0f',sETP.intImportStretch),...
		'Tooltip','# of frames to import for each time point');
	
	%% import frame button
	%button
	sFigETP.ptrButtonAcceptParams = uicontrol('Parent',hPanelDatimex,...
		'Units','normalized',...
		'Style','pushbutton',...
		'Position',[vecX(4) 0.1 dblButtonWidth dblHeight],...
		'FontSize',10,...
		'String',sprintf('Import'),...
		'Callback',{@ETP_ImportFrames},...;
		'Tooltip','Import new frames from video');
	
	%% import data
	ETP_ImportFrames([],[],true);
	
	%show panel
	set(hPanelDatimex,'Visible','on');
end